[tox]
envlist = py,ruff,mypy
minversion = 4.0
skipsdist = false

[testenv]
runner = uv-venv-lock-runner
extras = test
pass_env = WZB_TEST_DATABASE_DSN
commands = pytest {posargs} workspace_zulip_bridge/tests

[testenv:ruff]
runner = uv-venv-lock-runner
extras = ruff
commands =
    ruff check .
    ruff format --check .

[testenv:mypy]
runner = uv-venv-lock-runner
extras = mypy
commands = mypy -p workspace_zulip_bridge

[testenv:develop]
runner = uv-venv-lock-runner
extras = test,mypy,ruff
usedevelop = true
